import type { App } from 'vue';
import { installDanQingFeedback } from '@danqing/dq-shell';
import {
  DqAlert,
  DqButton,
  DqCheckbox,
  DqCheckboxGroup,
  DqCol,
  DqCollapse,
  DqCollapseItem,
  DqCountBadge,
  DqDatePicker,
  DqDialog,
  DqDrawer,
  DqDropdown,
  DqDropdownItem,
  DqDropdownMenu,
  DqEmpty,
  DqIcon,
  DqIconButton,
  DqInput,
  DqInputNumber,
  DqInspectorCallout,
  DqInspectorEmpty,
  DqInspectorKv,
  DqInspectorList,
  DqInspectorListItem,
  DqInspectorSection,
  DqInspectorSectionBody,
  DqInspectorStack,
  DqOption,
  DqPrefPane,
  DqPrefRow,
  DqProgress,
  DqRow,
  DqSectionTabPanel,
  DqSectionTabs,
  DqSectionTabTrigger,
  DqSegmented,
  DqSelect,
  DqSlider,
  DqStack,
  DqSurfaceCard,
  DqSwitch,
  DqTag,
  DqText,
  DqTooltip,
} from '@danqing/dq-shell';

const DQ_COMPONENTS = {
  DqSectionTabs,
  DqSectionTabTrigger,
  DqSectionTabPanel,
  DqButton,
  DqIconButton,
  DqDialog,
  DqDrawer,
  DqEmpty,
  DqTag,
  DqCountBadge,
  DqAlert,
  DqProgress,
  DqTooltip,
  DqCollapse,
  DqCollapseItem,
  DqText,
  DqStack,
  DqRow,
  DqCol,
  DqSegmented,
  DqSurfaceCard,
  DqInspectorStack,
  DqInspectorSection,
  DqInspectorSectionBody,
  DqInspectorEmpty,
  DqInspectorList,
  DqInspectorListItem,
  DqInspectorCallout,
  DqInspectorKv,
  DqPrefPane,
  DqPrefRow,
  DqInput,
  DqSelect,
  DqOption,
  DqSlider,
  DqSwitch,
  DqCheckbox,
  DqCheckboxGroup,
  DqInputNumber,
  DqDatePicker,
  DqIcon,
  DqDropdown,
  DqDropdownMenu,
  DqDropdownItem,
} as const;

/** DanQing design-system components (macOS desktop). */
export function installDanQingUi(app: App) {
  installDanQingFeedback(app);
  for (const [name, component] of Object.entries(DQ_COMPONENTS)) {
    app.component(name, component);
  }
}
