"""FIBO Wan2.2 VAE weight mapping (diffusers ``vae/*.safetensors``)."""
from __future__ import annotations

from typing import List

from backend.engine.common.bundle.weight_mapping import WeightTarget, WeightTransforms

class FiboVaeWeightMapping:
    @staticmethod
    def get_vae_mapping() -> List[WeightTarget]:
        return [
                WeightTarget(
                    to_pattern="encoder.conv_in.conv3d.weight",
                    from_pattern=["encoder.conv_in.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.conv_in.conv3d.bias",
                    from_pattern=["encoder.conv_in.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.norm1.weight",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.norm1.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv1.conv3d.weight",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv1.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv1.conv3d.bias",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv1.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.norm2.weight",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.norm2.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv2.conv3d.weight",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv2.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv2.conv3d.bias",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv2.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.conv3d.weight",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.conv3d.bias",
                    from_pattern=["encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.downsampler.resample_conv.weight",
                    from_pattern=["encoder.down_blocks.{block}.downsampler.resample.1.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.downsampler.resample_conv.bias",
                    from_pattern=["encoder.down_blocks.{block}.downsampler.resample.1.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.downsampler.time_conv.conv3d.weight",
                    from_pattern=["encoder.down_blocks.{block}.downsampler.time_conv.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.down_blocks.{block}.downsampler.time_conv.conv3d.bias",
                    from_pattern=["encoder.down_blocks.{block}.downsampler.time_conv.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.norm1.weight",
                    from_pattern=["encoder.mid_block.resnets.{i}.norm1.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.conv1.conv3d.weight",
                    from_pattern=["encoder.mid_block.resnets.{i}.conv1.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.conv1.conv3d.bias",
                    from_pattern=["encoder.mid_block.resnets.{i}.conv1.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.norm2.weight",
                    from_pattern=["encoder.mid_block.resnets.{i}.norm2.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.conv2.conv3d.weight",
                    from_pattern=["encoder.mid_block.resnets.{i}.conv2.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.resnets.{i}.conv2.conv3d.bias",
                    from_pattern=["encoder.mid_block.resnets.{i}.conv2.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.attentions.{i}.norm.weight",
                    from_pattern=["encoder.mid_block.attentions.{i}.norm.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.attentions.{i}.to_qkv.weight",
                    from_pattern=["encoder.mid_block.attentions.{i}.to_qkv.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.attentions.{i}.to_qkv.bias",
                    from_pattern=["encoder.mid_block.attentions.{i}.to_qkv.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.attentions.{i}.proj.weight",
                    from_pattern=["encoder.mid_block.attentions.{i}.proj.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.mid_block.attentions.{i}.proj.bias",
                    from_pattern=["encoder.mid_block.attentions.{i}.proj.bias"],
                ),
                WeightTarget(
                    to_pattern="encoder.norm_out.weight",
                    from_pattern=["encoder.norm_out.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="encoder.conv_out.conv3d.weight",
                    from_pattern=["encoder.conv_out.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="encoder.conv_out.conv3d.bias",
                    from_pattern=["encoder.conv_out.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.conv_in.conv3d.weight",
                    from_pattern=["decoder.conv_in.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.conv_in.conv3d.bias",
                    from_pattern=["decoder.conv_in.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.norm1.weight",
                    from_pattern=["decoder.mid_block.resnets.{i}.norm1.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.conv1.conv3d.weight",
                    from_pattern=["decoder.mid_block.resnets.{i}.conv1.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.conv1.conv3d.bias",
                    from_pattern=["decoder.mid_block.resnets.{i}.conv1.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.norm2.weight",
                    from_pattern=["decoder.mid_block.resnets.{i}.norm2.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.conv2.conv3d.weight",
                    from_pattern=["decoder.mid_block.resnets.{i}.conv2.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.resnets.{i}.conv2.conv3d.bias",
                    from_pattern=["decoder.mid_block.resnets.{i}.conv2.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.attentions.{i}.norm.weight",
                    from_pattern=["decoder.mid_block.attentions.{i}.norm.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.attentions.{i}.to_qkv.weight",
                    from_pattern=["decoder.mid_block.attentions.{i}.to_qkv.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.attentions.{i}.to_qkv.bias",
                    from_pattern=["decoder.mid_block.attentions.{i}.to_qkv.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.attentions.{i}.proj.weight",
                    from_pattern=["decoder.mid_block.attentions.{i}.proj.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.mid_block.attentions.{i}.proj.bias",
                    from_pattern=["decoder.mid_block.attentions.{i}.proj.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.norm1.weight",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.norm1.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv1.conv3d.weight",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv1.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv1.conv3d.bias",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv1.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.norm2.weight",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.norm2.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv2.conv3d.weight",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv2.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv2.conv3d.bias",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv2.bias"],
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.conv3d.weight",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.conv3d.bias",
                    from_pattern=["decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.upsampler.time_conv.conv3d.weight",
                    from_pattern=["decoder.up_blocks.{block}.upsampler.time_conv.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.upsampler.time_conv.conv3d.bias",
                    from_pattern=["decoder.up_blocks.{block}.upsampler.time_conv.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.upsampler.resample_conv.weight",
                    from_pattern=["decoder.up_blocks.{block}.upsampler.resample.1.weight"],
                    transform=WeightTransforms.transpose_conv2d_weight,
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.up_blocks.{block}.upsampler.resample_conv.bias",
                    from_pattern=["decoder.up_blocks.{block}.upsampler.resample.1.bias"],
                    required=False,
                ),
                WeightTarget(
                    to_pattern="decoder.norm_out.weight",
                    from_pattern=["decoder.norm_out.gamma"],
                    transform=WeightTransforms.reshape_gamma_to_1d,
                ),
                WeightTarget(
                    to_pattern="decoder.conv_out.conv3d.weight",
                    from_pattern=["decoder.conv_out.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="decoder.conv_out.conv3d.bias",
                    from_pattern=["decoder.conv_out.bias"],
                ),
                WeightTarget(
                    to_pattern="quant_conv.conv3d.weight",
                    from_pattern=["quant_conv.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="quant_conv.conv3d.bias",
                    from_pattern=["quant_conv.bias"],
                ),
                WeightTarget(
                    to_pattern="post_quant_conv.conv3d.weight",
                    from_pattern=["post_quant_conv.weight"],
                    transform=WeightTransforms.transpose_conv3d_weight,
                ),
                WeightTarget(
                    to_pattern="post_quant_conv.conv3d.bias",
                    from_pattern=["post_quant_conv.bias"],
                ),
        ]


class _FiboVaeWeightDefinition:
    @staticmethod
    def get_components():
        from backend.engine.common.bundle.bundle_weights.definitions import ComponentDefinition

        return [
            ComponentDefinition(
                name="vae",
                hf_subdir="vae",
                num_blocks=4,
                loading_mode="mlx_native",
                mapping_getter=FiboVaeWeightMapping.get_vae_mapping,
            )
        ]

    @staticmethod
    def get_download_patterns():
        return ["vae/*.safetensors"]
