"""Engine shared layer — facade only; implementations live in subpackages.

Subpackages:
  ops/       — attention, norm, embeddings, schedulers, …
  model/     — TransformerBase, DelegatingDiTStem
  bundle/    — weights I/O, bundle layout, cross-family LoRA merge
  codecs/    — cross-family text encoders & VAE (T5, CLIP, Qwen3, AutoencoderKL)

Engine-level: ``cache.py``, ``lineage.py``, ``contracts/``, ``runtime/`` (see ``docs/engine_architecture.md`` §3).
Pipeline/family runtime semantics live in ``backend/engine/contracts/``.
"""
from backend.core.contracts import CancelToken

from backend.engine.common.bundle.weights import (
    LoRAConfig,
    inject_lora,
    load_lora_weights,
    load_safetensors,
    parse_size_gb,
    quantize_weights,
    save_safetensors,
)
from backend.engine.common.codecs.text_encoders import CLIPEncoder, T5Encoder
from backend.engine.common.codecs.vae import remap_vae_weights
from backend.engine.common.ops.activations import gelu, silu
from backend.engine.common.ops.attention import (
    CrossAttention,
    SelfAttention,
    TemporalAttention,
    apply_binary_mask_bias,
    attention_bhsd,
    attention_bhsd_to_blhd,
    attention_blhd,
    build_bidirectional_bool_attention_mask,
    build_causal_attention_mask,
    build_causal_with_offset_bias,
    build_causal_with_padding_bias,
    build_frame_prefix_causal_bias,
    build_key_padding_mask_from_lengths,
    build_padding_attention_bias,
    build_window_with_padding_bias,
    build_window_with_padding_bias_torch,
    left_pad_token_mask,
    repeat_kv_heads_mx,
    repeat_kv_heads_torch,
    resolve_blhd_attention_mask,
    scaled_dot_product_attention_bhsd_mx,
    scaled_dot_product_attention_bhsd_torch,
)
from backend.engine.common.ops.embeddings import (
    PatchEmbed2D,
    PatchEmbed3D,
    RoPE2D,
    RoPE3D,
    TimestepEmbedding,
    TimestepEmbeddingMLP,
    apply_complex_rope_bshd,
    apply_complex_rope_from_cis_bshd,
    build_position_ids_2d,
    build_position_ids_3d_axes,
    factorized_rope_apply,
    factorized_rope_concat_params,
    factorized_rope_params,
    factorized_rope_precompute_cos_sin,
    pad_len_to_multiple,
    pad_ragged_1d_sequences,
    pad_ragged_2d_sequences,
    pad_tail_with_last,
    apply_pad_token,
    build_tail_pad_mask,
    sinusoidal_embedding_1d,
    sinusoidal_timestep_proj,
)
from backend.engine.common.ops.norm import (
    AdaLayerNorm,
    GroupNorm,
    LayerNorm,
    RMSNorm,
    apply_ada_layer_norm_continuous,
    apply_ada_layer_norm_zero,
    apply_ada_layer_norm_zero_single,
    apply_layer_norm_fp32,
    apply_rms_norm,
    apply_scale_shift,
    split_last_dim_chunks,
    unpack_modulation_2table,
    unpack_modulation_2way,
    unpack_modulation_3way,
    unpack_modulation_4way,
    unpack_modulation_6table,
    unpack_modulation_6way,
)
from backend.engine.common.ops.schedulers import (
    DPMPlusPlusScheduler,
    FlowMatchEulerScheduler,
    LinearScheduler,
    Scheduler,
    SeedVR2EulerScheduler,
    UniPCScheduler,
    get_scheduler,
)
from backend.engine.cache import ModelCache
from backend.engine.contracts.runtime_contracts import (
    FamilyRuntimeContract,
    SchedulerSemantics,
    SchedulerSemanticsResolver,
)

__all__ = [
    "Scheduler",
    "FlowMatchEulerScheduler",
    "LinearScheduler",
    "UniPCScheduler",
    "DPMPlusPlusScheduler",
    "SeedVR2EulerScheduler",
    "get_scheduler",
    "RMSNorm",
    "LayerNorm",
    "GroupNorm",
    "AdaLayerNorm",
    "apply_rms_norm",
    "apply_layer_norm_fp32",
    "apply_scale_shift",
    "apply_ada_layer_norm_continuous",
    "apply_ada_layer_norm_zero",
    "apply_ada_layer_norm_zero_single",
    "split_last_dim_chunks",
    "unpack_modulation_2way",
    "unpack_modulation_3way",
    "unpack_modulation_4way",
    "unpack_modulation_6way",
    "unpack_modulation_2table",
    "unpack_modulation_6table",
    "silu",
    "gelu",
    "SelfAttention",
    "CrossAttention",
    "TemporalAttention",
    "attention_blhd",
    "attention_bhsd",
    "attention_bhsd_to_blhd",
    "scaled_dot_product_attention_bhsd_mx",
    "scaled_dot_product_attention_bhsd_torch",
    "repeat_kv_heads_mx",
    "repeat_kv_heads_torch",
    "build_key_padding_mask_from_lengths",
    "build_causal_attention_mask",
    "build_padding_attention_bias",
    "resolve_blhd_attention_mask",
    "build_bidirectional_bool_attention_mask",
    "left_pad_token_mask",
    "apply_binary_mask_bias",
    "build_causal_with_padding_bias",
    "build_causal_with_offset_bias",
    "build_window_with_padding_bias",
    "build_window_with_padding_bias_torch",
    "build_frame_prefix_causal_bias",
    "TimestepEmbedding",
    "TimestepEmbeddingMLP",
    "sinusoidal_embedding_1d",
    "sinusoidal_timestep_proj",
    "RoPE2D",
    "RoPE3D",
    "factorized_rope_params",
    "factorized_rope_concat_params",
    "factorized_rope_precompute_cos_sin",
    "factorized_rope_apply",
    "build_position_ids_2d",
    "build_position_ids_3d_axes",
    "pad_ragged_2d_sequences",
    "pad_ragged_1d_sequences",
    "pad_len_to_multiple",
    "build_tail_pad_mask",
    "pad_tail_with_last",
    "apply_pad_token",
    "apply_complex_rope_bshd",
    "apply_complex_rope_bhsd",
    "apply_complex_rope_from_cis_bshd",
    "PatchEmbed2D",
    "PatchEmbed3D",
    "parse_size_gb",
    "load_safetensors",
    "save_safetensors",
    "LoRAConfig",
    "load_lora_weights",
    "inject_lora",
    "quantize_weights",
    "remap_vae_weights",
    "ModelCache",
    "CancelToken",
    "T5Encoder",
    "CLIPEncoder",
    "FamilyRuntimeContract",
    "SchedulerSemanticsResolver",
    "SchedulerSemantics",
]
